### ISSUE TITLE
Config corrompue, message "Un problème est survenu lors de la génération de la page.

### ISSUE THREAD

**Issue by hamelg** [Blount/Cheky#84]
Je ré-ouvre ce ticket.
https://github.com/Blount/LBCAlerte/issues/53

Pour résoudre ce souci, j'ai remplacé la ligne ci-dessous dans le fichier bootstrap.php : 

$config = new Config_Lite(DOCUMENT_ROOT."/var/config.ini");
par
$config = new Config_Lite(DOCUMENT_ROOT."/var/config.ini", LOCK_EX);

De cette façon, il n'y a plus que un seul thread qui peut modifier le fichier config.ini au même moment.

**Comment by Blount** [comment]
Bonjour.
Modification intégrée dans la version 4.4.

Merci.
