### ISSUE TITLE
Recevoir les annonces toutes les minutes

### ISSUE THREAD

**Issue by vitoo** [Blount/Cheky#85]
Bonjour,

j'ai réglé le temps d'interval à 0 min afin de ne pas être limité, mais je ne reçois pas les annonces toutes les minutes, est-ce possible ?

Par exemple je n'ai pas recu l'annonce de 13h54 aujourd'hui : 

https://www.leboncoin.fr/ventes_immobilieres/offres/nord_pas_de_calais/?th=1&location=Lille&ps=9&pe=14&sqs=10&ros=3&ret=1

Merci pour votre aide

**Comment by Blount** [comment]
Bonjour,
En plus du temps sur les alertes, il faut aussi régler le temps sur la tâche CRON.
Si elle s'exécute toutes les 5 minutes par exemple, le temps minimum par alerte sera de 5 minutes. Il faut donc mettre une exécution toutes les minutes pour la tâche automatique.

**Comment by vitoo** [comment]
Oui ma tache cron est sur toute les minutes

Bon les annonces que je ne recois pas doivent être des repost peut-être ...

Aussi, la date de l'annonce correspond à la date de validation par leboncoin ou la date de création ?

**Comment by Blount** [comment]
Si ta tâche et ton alerte sont configurées sur 1 minute, je ne pense pas qu'il y ait un souci.
Comme tu le fait remarquer, la date correspond à la mise en ligne sur Leboncoin. Ils peuvent valider un annonce sans qu'elle soit mise en ligne immédiatement.
En outre, une annonce peut être mise en ligne avec une date "retravaillée" qui ne correspond pas à la vrai date. Finalement, la vrai date de publication, c'est c'est au moment où tu reçoit l'alerte ^^

**Comment by vitoo** [comment]
Super merci :)
