### ISSUE TITLE
Error in 4.0 Unknown column 'error_count' 

### ISSUE THREAD

**Issue by cpecquerie** [Blount/Cheky#90]
This appears when updating or creating a new alert.

2018-07-02T10:59:30+02:00 ERROR mysqli_sql_exception : #1054 Unknown column 'error_count' in 'field list' (/home/cpecque/public_html/lbcalerte/app/models/Storage/Db/Alert.php:95)

**Comment by Blount** [comment]
Can you update to 4.0.1 and report me if this bug is solved ?

**Comment by cpecquerie** [comment]
Yes, corrected ! Thanks 😉

De : Blount <notifications@github.com>
Répondre à : Blount/Cheky <reply@reply.github.com>
Date : lundi 2 juillet 2018 à 11:12
À : Blount/Cheky <Cheky@noreply.github.com>
Cc : Christophe Pecquerie <cpecquerie@gmail.com>, Author <author@noreply.github.com>
Objet : Re: [Blount/Cheky] Error in 4.0 Unknown column 'error_count' (#90)


Can you update to 4.0.1 and report me if this bug is solved ?

**Comment by Blount** [comment]
Thank you very much for your report :)
