### ISSUE TITLE
Alerte Seloger : L'adresse de recherche a généré une erreur 307.

### ISSUE THREAD

**Issue by AlgoN1** [Blount/Cheky#91]
tous mes alertes Seloger ne fonctionnent pas. Je reparamètre à chaque fois. Dans un premier temps ça marche bien mais après ça donne ce message "Une erreur a été rencontrée sur l'alerte :
L'adresse de recherche a généré une erreur 307." et je recommence au moins deux fois dans la journée.

**Comment by Blount** [comment]
Corrigé dans la dernière version.
Merci
