### ISSUE TITLE
L'adresse indiquée a généré une erreur 403.

### ISSUE THREAD

**Issue by chreggy** [Blount/Cheky#93]
Hello,

depuis le passage de la 3.9 à la 4.1, on ne peux plus créer de nouvelles alertes leboncoin (entre autre) car le système écrit en rouge "L'adresse indiquée a généré une erreur 403.". Ca fonctionnait parfaitement avec la version d'avant et je ne sais pas revenir en arrière...

D'autres personnes ont le même problème sur le forum.

Merci :o)

**Comment by Draky50110** [comment]
News here : https://github.com/RSS-Bridge/rss-bridge/issues/789
@Blount si ça peut aider...

**Comment by Blount** [comment]
Cheky est à nouveau fonctionnelle dans sa dernière version 4.3.1.

**Comment by chreggy** [comment]
Merci. :o)
