### ISSUE TITLE
Erreur "curl error" 

### ISSUE THREAD

**Issue by arnogues** [Blount/Cheky#94]
Quand je veux rajouter une alerte pour leboncoin, je me retrouve avec l'erreur "Curl error"
Sachant que j'utilise piost.net, est-ce que ça viendrait de là ?

**Comment by C-Duv** [comment]
J'ai pareil, ainsi que « L'adresse indiquée a généré une erreur 403 » (cf. #93).
Ça doit venir de leur système Datadome (cf. RSS-Bridge/rss-bridge#789).

**Comment by Blount** [comment]
Bonjour,
Leboncoin a mis en place un système de protection plus poussé, bloquant les accès de type "robot" comme le fait Cheky.
Finalement, j'ai pu mettre à niveau Cheky afin de rendre à nouveau opérationnel les alertes.
Il faut donc mettre à jour Cheky pour ceux qui l'ont installé de leur coté.
Pour Piost, actuellement les comptes premium sont à nouveau actifs, j'attends de voir commet ca tourne avant de remettre aussi les comptes gratuits.
