### ISSUE TITLE
Erreur 403 bloqué 

### ISSUE THREAD

**Issue by vitoo** [Blount/Cheky#95]
Depuis mon dédié j'ai une 403 au curl, voici le résultat : 

Need permission to access data? Contact: DataAccess@datadome.co

<html><head><title>You have been blocked</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={'cid':'AHrlqAAAAAMAVz90RbQ_jgUAuSNAdQ==','hsh':'05B30BD9055986BD2EE8F5A199D973'}</script><script src="https://ct.datadome.co/c.js"></script></body></html>

Suis-je le seul ?

**Comment by Blount** [comment]
Bonjour,
Quelle version de Cheky utilises-tu ?
C'est un problème connu et on en parle depuis quelques temps sur le forum : 
https://forum.cheky.net/erreur-403-t605-p1.html

Normalement, la dernière version de Cheky est toujours fonctionnelle.

**Comment by vitoo** [comment]
Version 4.1

**Comment by vitoo** [comment]
En effet avec la MAJ c'est bon

merci :)
