### ISSUE TITLE
"-" (tiret) dans l'url : CURL error

### ISSUE THREAD

**Issue by emmanuelvargas** [Blount/Cheky#97]
Hello

Si il y a un tiret dans la recherche, on a un joli "curl error" qui apparait.
Enfin du moins la par exemple je cherche le model "C-MAX" (cest un champs rempli automagiquement par leboncoin)

NOK : 
https://www.leboncoin.fr/recherche/?category=2&regions=12&region_near=1&model=C-max&brand=Ford&mileage=min-100000&price=min-11000&regdate=2014-max

OK : 
https://www.leboncoin.fr/recherche/?category=2&regions=12&region_near=1&model=Cmax&brand=Ford&mileage=min-100000&price=min-11000&regdate=2014-max

(OUi je sais je cherche une voiture :) )

**Comment by Blount** [comment]
Résolu dans la dernière version, merci pour le retour.
